[voting_service]

[voting_service.db]
dbname = "voting_db"
host = "localhost"
port = 5432
username = "voting_user"
password = "secret"

[web_api]
host = "localhost"
port = 8080
read_timeout = 10
shutdown_timeout = 5