[voting_service]

[voting_service.db]
dbname = "voting_db"
host = "localhost"
port = 5432
username = "user"
password = "secret"

[voting_service.webapi]
host = "0.0.0.0"
port = 8080
read_timeout = 10
shutdown_timeout = 5